analyzer:
  errors: 
    unrelated_type_equality_checks: error
    camel_case_types: error
    close_sinks: error

    avoid_empty_else: warning
    constant_identifier_names: warning
    empty_constructor_bodies: warning
    unnecessary_statements: warning
    non_constant_identifier_names: warning
    require_trailing_commas: warning
    

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    unrelated_type_equality_checks: true
    camel_case_types: true
    close_sinks: true

    avoid_empty_else: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    unnecessary_statements: true
    non_constant_identifier_names: true
    require_trailing_commas: true

